version: '3'

services:
  postgres:
    image: "postgres:16.3"
    container_name: "java-postgres"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=2215"
      - "POSTGRES_DB=data_storage"
  app:
    build: ./
    container_name: "java-app"
    ports:
      - 8080:8080